name: Android Build

on:
  push:
    branches: [ axis ]
  pull_request:
    branches: [ axis ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          local-cache: true

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Set SDK and NDK path
        run: |
          echo "SDK_PATH=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "NDK_PATH=$ANDROID_NDK_ROOT" >> $GITHUB_ENV

      - name: Build Android
        run: make build-android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
