name: Build and Deploy Web Version

on:
  push:
    branches: [ axis ]
  pull_request:
    branches: [ axis ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Step 2: Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      # Step 3: Set up Emscripten using Nix
      - name: Set up Emscripten with Nix
        run: |
          nix-env -iA nixpkgs.emscripten

      # Step 4: Install xmake directly
      - name: Install xmake
        run: |
          wget https://xmake.io/shget.text -O - | bash
          source ~/.xmake/profile

      # Step 5: Build for Web (WASM)
      - name: Build for Web (WASM)
        run: |
          xmake f -p wasm -y
          xmake -y

      # Step 6: Prepare artifacts
      - name: Prepare artifacts
        run: |
          mkdir -p netlify-build
          cp -r build/clay/* netlify-build/
          cp index.html netlify-build/
          cp manifest.json netlify-build/
          cp -r fonts netlify-build/
          cp -r images netlify-build/

      # Step 7: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './netlify-build'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}