name: Linux Build

on:
  push:
    branches: [ axis ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ axis ]

permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, i686, arm64, armv7, armv6, riscv64]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Add Architecture Support
        run: |
          sudo dpkg --add-architecture i386
          sudo dpkg --add-architecture arm64
          sudo dpkg --add-architecture armhf
          sudo dpkg --add-architecture riscv64
          sudo apt-get update

      - name: Install Common Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libsdl2-gfx-dev \
            libpng-dev \
            libfreetype6-dev \
            libwebp-dev \
            libtiff-dev \
            libjpeg-dev \
            libharfbuzz-dev \
            libgraphite2-dev \
            wayland-protocols \
            libwayland-dev \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxfixes-dev \
            libxi-dev \
            libxss-dev \
            libxxf86vm-dev \
            libgl1-mesa-dev

      - name: Install Architecture-Specific Dependencies
        run: |
          if [ "${{ matrix.arch }}" = "i686" ]; then
            sudo apt-get install -y \
              gcc-multilib \
              libsdl2-dev:i386 \
              libsdl2-image-dev:i386 \
              libsdl2-ttf-dev:i386 \
              libsdl2-gfx-dev:i386
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo apt-get install -y \
              gcc-aarch64-linux-gnu \
              libsdl2-dev:arm64 \
              libsdl2-image-dev:arm64 \
              libsdl2-ttf-dev:arm64 \
              libsdl2-gfx-dev:arm64
          elif [ "${{ matrix.arch }}" = "armv7" ] || [ "${{ matrix.arch }}" = "armv6" ]; then
            sudo apt-get install -y \
              gcc-arm-linux-gnueabihf \
              libsdl2-dev:armhf \
              libsdl2-image-dev:armhf \
              libsdl2-ttf-dev:armhf \
              libsdl2-gfx-dev:armhf
          elif [ "${{ matrix.arch }}" = "riscv64" ]; then
            sudo apt-get install -y \
              gcc-riscv64-linux-gnu \
              libsdl2-dev:riscv64 \
              libsdl2-image-dev:riscv64 \
              libsdl2-ttf-dev:riscv64 \
              libsdl2-gfx-dev:riscv64
          fi

      - name: Install xmake
        run: |
          wget https://xmake.io/shget.text -O - | bash
          source ~/.xmake/profile

      - name: Build with xmake
        continue-on-error: true
        id: build
        run: |
          xmake clean
          xmake f -p linux -a ${{ matrix.arch }} -y
          xmake -y

      - name: Rename binary
        if: steps.build.outcome == 'success'
        run: |
          mkdir -p artifacts
          cp build/clay/main artifacts/myquest-linux-${{ matrix.arch }}
          chmod +x artifacts/myquest-linux-${{ matrix.arch }}

      - name: Upload Artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.arch }}-build
          path: artifacts/myquest-linux-${{ matrix.arch }}
      
      - name: Generate date
        id: date
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create Nightly Release
        if: "!startsWith(github.ref, 'refs/tags/')"
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ steps.date.outputs.date }}
          name: Development Build ${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
          files: |
            artifacts/myquest-linux-${{ matrix.arch }}

      - name: Create Tagged Release
        if: startsWith(github.ref, 'refs/tags/')
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/myquest-linux-${{ matrix.arch }}