name: Windows Build

on:
  push:
    branches: [ axis ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ axis ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-libwebp
            unzip

      - name: Install xmake
        run: |
          wget https://github.com/xmake-io/xmake/releases/download/v2.8.9/xmake-v2.8.9.win64.zip -O xmake.zip
          unzip xmake.zip
          export PATH="$PWD/xmake:$PATH"

      - name: Build with xmake
        run: |
          export PATH="/mingw64/bin:$PATH"
          xmake clean
          xmake f -p windows -y
          xmake -y

      - name: Copy DLL Dependencies
        run: |
          mkdir -p build/clay
          cp build/windows/x64/release/main.exe build/clay/
          cp /mingw64/bin/SDL2.dll build/clay/
          cp /mingw64/bin/SDL2_image.dll build/clay/
          cp /mingw64/bin/SDL2_ttf.dll build/clay/
          cp /mingw64/bin/SDL2_gfx-1-0-0.dll build/clay/
          cp /mingw64/bin/libwinpthread-1.dll build/clay/
          cp /mingw64/bin/libstdc++-6.dll build/clay/
          cp /mingw64/bin/libgcc_s_seh-1.dll build/clay/
          cp /mingw64/bin/zlib1.dll build/clay/
          cp /mingw64/bin/libpng16-16.dll build/clay/
          cp /mingw64/bin/libjpeg-8.dll build/clay/
          cp /mingw64/bin/libfreetype-6.dll build/clay/

      - name: Create ZIP Archive
        run: |
          cd build
          7z a -tzip windows-build.zip clay/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows-build.zip
      
      - name: Generate timestamp
        id: timestamp
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: echo "timestamp=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create Nightly Release
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ steps.timestamp.outputs.timestamp }}
          name: Development Build ${{ steps.timestamp.outputs.timestamp }}
          draft: false
          prerelease: true
          files: |
            build/windows-build.zip

      - name: Create Tagged Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            build/windows-build.zip